(function(){'use strict';const CONFIG={observerOptions:{root:null,threshold:0.1,rootMargin:'50px'},selectors:{animatedElements:'.hidden, .feat, .srv, .special-heading, .project-modern',landingSection:'.landing',projectImages:'.main-project-img, .vision-hero-img img, .vision-img img, .section-img'}};function createGeneralObserver(){const observer=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}})},CONFIG.observerOptions);return observer}
function createProjectObserver(){const observer=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible')}else{entry.target.classList.remove('visible')}})},CONFIG.observerOptions);return observer}
function initObservers(){const generalObserver=createGeneralObserver();const projectObserver=createProjectObserver();document.querySelectorAll(CONFIG.selectors.animatedElements).forEach(element=>{if(element.classList.contains('project-modern')){projectObserver.observe(element)}else{generalObserver.observe(element)}});document.querySelectorAll('.special-heading').forEach(heading=>{generalObserver.observe(heading);const nextElement=heading.nextElementSibling;if(nextElement&&nextElement.tagName==='P'){generalObserver.observe(nextElement)}})}
function animateLanding(){const landingSection=document.querySelector(CONFIG.selectors.landingSection);if(landingSection){landingSection.classList.add('loaded')}
document.body.classList.add('loaded')}
function animateProjectImages(){document.querySelectorAll(CONFIG.selectors.projectImages).forEach(img=>{setTimeout(()=>{img.classList.add('visible')},Math.random()*200)})}
function optimizePerformance(){if(window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches){document.documentElement.style.setProperty('--transition','0.01s');return}
function rafThrottle(fn){let ticking=!1;return function(...args){if(!ticking){requestAnimationFrame(()=>{fn.apply(this,args);ticking=!1});ticking=!0}}}
const throttledScroll=rafThrottle(()=>{});window.addEventListener('scroll',throttledScroll,{passive:!0})}
function handleErrors(){window.addEventListener('error',(e)=>{console.warn('Animation error:',e.error)})}
function init(){try{if(!('IntersectionObserver' in window)){document.querySelectorAll(CONFIG.selectors.animatedElements).forEach(el=>{el.classList.add('visible')});return}
initObservers();optimizePerformance();handleErrors();if(document.readyState==='loading'){window.addEventListener('load',animateLanding)}else{animateLanding()}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',animateProjectImages)}else{animateProjectImages()}}catch(error){console.warn('Animation initialization failed:',error);document.querySelectorAll(CONFIG.selectors.animatedElements).forEach(el=>{el.classList.add('visible')})}}
init()})()